### ISSUE TITLE
Can't setup when using fabric loom

### ISSUE THREAD

**Issue by wdog5** [FabricMC/fabric-loom#1041]
It can be happend sometimes, even I delete all cache of .gralde or delete all cache,it is still happend when using fabric loom
maybe about "net.fabricmc.loom.configuration.providers.mappings.IntermediateMappingsService"?
It is only happend when using fabric loom
Logs below:
[log.txt](https://github.com/FabricMC/fabric-loom/files/14155271/log.txt)

**Comment by SNWCreations** [comment]
It seems that this is a dependency conflict. Check your usage about Guava?

**Comment by wdog5** [comment]
I delete all of the cache,it is not effective

**Comment by SNWCreations** [comment]
I think it is not caused by cache, maybe you specified a version of Guava, and loom wanted another version...

I'm not sure. Check if your code used things in Guava and downgrade Guava, see correct version in Loom's build script.
If you don't have Guava specified in your script, I have no idea. ¯\_(ツ)_/¯

**Comment by modmuss50** [comment]
Do you have any other plugins, this is possibly related to: https://github.com/FabricMC/fabric-loom/issues/1020

**Comment by modmuss50** [comment]
Closing as no response
