### ISSUE TITLE
Importing the Gradle project in IDEA causes issues with finding Launchwrapper

### ISSUE THREAD

**Issue by asiekierka** [FabricMC/fabric-loom#22]
From quat:

```When I clone from Github, gradlew idea, then open the generated .ipr in idea, things seem to work maybe sorta. I can use the Minecraft Client run configuration and the game starts. I don't think the mixin worked (ctrl-f the log for This line is printed by an example mod mixin! 0 results, but also 0 errors...).

When I enable the Gradle tool window, that's when it starts breaking due to being unable to find launchwrapper.
Like, IDEA pops up "Unlined gradle project? Import Gradle project!", I press ok to make it shut up and also since it's a forgegradle habit, and that's when the run configuration stops working.```

**Comment by SquidDev** [comment]
I've had a similar issue, where Loom was generating the run configurations targetting the top-level project, rather than the `Whatever_main` project, which means Minecraft wasn't on the classpath. Not sure if this was the cause here however.

**Comment by modmuss50** [comment]
For @SquidDev issue, this happens when `Create separate module per source set` is selected. (It is by default) 

This is being set 

https://github.com/FabricMC/fabric-loom/blob/dev/src/main/java/net/fabricmc/loom/util/IdeaRunConfig.java#L92

I will need to figure out if there is a way to get the correct name, if not im not sure what can be done.


quat's could be the same thing, however I will need to test this

**Comment by modmuss50** [comment]
![idea64_2018-12-10_14-33-22](https://user-images.githubusercontent.com/4324090/49738952-95932380-fc88-11e8-8d1d-108c5d8ab849.png)

When you press that button it changes the module name, to fix it not finding launch wrapper you have to change the module the run config uses to -main.

Finding a way to generate the run configs with the correct module would be nice

**Comment by modmuss50** [comment]
Nothing I can do about this issue, just set the module name.
