### ISSUE TITLE
ClassNotFoundException thrown during compileJava task

### ISSUE THREAD

**Issue by jpenilla** [FabricMC/fabric-loom#368]
loom: `Fabric Loom: 0.6.54 Build(release #54)`

When running `./gradlew build` in a clean workspace, or when running `./gradlew clean build`, the build will succeed, however will print the following stacktrace: https://paste.gg/p/anonymous/05bd677650944136bb5b38a44f4ce260

When running the build task a second time, the stacktrace is not present.

Here is the [EntitySelectorAccess](https://github.com/Incendo/cloud/blob/25bee05436f7c9c36a5a7d082a995b2a8af1f07d/cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/internal/EntitySelectorAccess.java) interface it seems to be complaining about, and [here](https://github.com/Incendo/cloud/blob/25bee05436f7c9c36a5a7d082a995b2a8af1f07d/cloud-minecraft/cloud-fabric/src/main/java/cloud/commandframework/fabric/mixin/EntitySelectorMixin.java) is the mixin using it.

edit: Having the same issue in another project now, the common thing seems to be implementing an interface using `@Implements` and a prefix, rather than normally implementing the interface in the mixin.

**Comment by zml2008** [comment]
This is probably an issue in `fabric-mixin-compile-extensions`: https://github.com/FabricMC/fabric-mixin-compile-extensions/blob/701fd122cfa14dc2d4dc091da5f3eafc1ae88401/src/main/java/net/fabricmc/loom/mixin/MixinMappingProviderTiny.java#L55

Not sure why it's trying to perform class loads there, but it's failing because the referenced class is in the source set being compiled, so not accessible on the annotation processor classpath.
