### ISSUE TITLE
Unable to set classifier correctly for jar archives

### ISSUE THREAD

**Issue by ChloeDawn** [FabricMC/fabric-loom#452]
**Version:** 0.8.21

No effect (ideally this is the approach that should work as expected):
```kt
tasks.jar {
	archiveClassifier.set("foo")
}
```
---
Produces a JAR with the correct classifier, but `-dev` jar with no prepended classifier:
```kt
afterEvaluate {
	tasks.remapJar {
		archiveClassifier.set("foo")
	}
}
```
```
Example-1.0.0-dev.jar
Example-1.0.0-foo.jar
```
---
Produces an error:
```kt
afterEvaluate {
	tasks.jar {
		archiveClassifier.set("foo")
	}
}

OR 

afterEvaluate {
	tasks.jar {
		archiveClassifier.set("foo")
	}

	tasks.remapJar {
		archiveClassifier.set("foo")
	}
}
```
```
A problem was found with the configuration of task ':remapJar' (type 'RemapJarTask').
  - In plugin 'net.fabricmc.loom.LoomRepositoryPlugin' type 'net.fabricmc.loom.task.RemapJarTask' property 'input' specifies file '...\build\libs\Example-1.0.0-dev.jar' which doesn't exist.
```

**Comment by ChloeDawn** [comment]
The problematic code that is breaking Gradle expectations can be found here
https://github.com/FabricMC/fabric-loom/blob/75234f4cbde7392f47a593b670b51cdda821e030/src/main/java/net/fabricmc/loom/configuration/RemapConfiguration.java#L73-L74

**Comment by Juuxel** [comment]
This seems to happen because of Loom's overuse of `afterEvaluate`. The remapJar task is configured in an `afterEvaluate` block in `CompileConfiguration`:
https://github.com/FabricMC/fabric-loom/blob/5d0c8ab0974bcbcc470adf29a4a1cabbc1a193a2/src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java#L127
...where it eventually ends up replacing whatever the user has set during the normal config phase:
https://github.com/FabricMC/fabric-loom/blob/5d0c8ab0974bcbcc470adf29a4a1cabbc1a193a2/src/main/java/net/fabricmc/loom/configuration/RemapConfiguration.java#L72-L76

In turn, the error you're getting happens because Loom uses the deprecated [`getArchivePath`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/bundling/AbstractArchiveTask.html#getArchivePath--). If it's replaced by the lazy [`getArchiveFile`](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/bundling/AbstractArchiveTask.html#getArchiveFile--) (as it should be - lazy properties prevent this very type of bug), it should not crash at least.

**Comment by Juuxel** [comment]
As a side note, the same `afterEvaluate` overuse leads to not being able to change other properties outside of `afterEvaluate`, like `remapAccessWidener` in [Adorn](https://github.com/Juuxel/Adorn/blob/a998616625042be0f2521218b1f5d93c34c82ba6/common/build.gradle.kts#L38-L45). Even the archive classifier that I set above would be broken, but Loom (luckily for me?) uses the deprecated `setClassifier` instead of `getArchiveClassifier().set()` so it's only used as a fallback.

Really, all of this code needs to be changed to a) use `Property` instead of deprecated archive task methods, and b) not be in `afterEvaluate`.

**Comment by ghost** [comment]
Should at least be partially solved in `0.10.26` after my PR yesterday which switched the `.set` to `.convention`

**Comment by modmuss50** [comment]
This was fixed.

**Comment by ChloeDawn** [comment]
What is the recommended implementation for archive classifiers? I cannot seem to get them to work correctly.

Setting the archive classifer for `jar` to `"fabric"` and `sourcesJar` to `"fabric-sources"` results in a remapped artifact with no classifier, and a non-remapped artifact with a classifier. Additionally setting the archive classifier for `remapJar` to `"fabric"` results in only an artifact with a classifier being generated, containing no classes.

Source artifacts seem to generate fine.

**Loom version:** 0.10.64

**Comment by Juuxel** [comment]
> Setting the archive classifer for jar to "fabric" and sourcesJar to "fabric-sources" results in a remapped artifact with no classifier, and a non-remapped artifact with a classifier

This works like expected. The `jar` task generates the named/non-remapped jar so for most cases, it's probably not useful to touch that in the first place. If you just want to edit the remapped jars, then changing `remapJar.archiveClassifier` is enough.

(not sure how the sources work since that task is implemented differently)

**Comment by ChloeDawn** [comment]
Omitting the archive classifier for `jar` (whilst including `"fabric"` for `remapJar`) results in a remapped `-fabric` artifact and a non-remapped `-dev` artifact. I would expect the non-remapped artifact to be `-fabric-dev` though, much like the `-fabric-sources-dev` artifact that is generated.

**Comment by Juuxel** [comment]
Loom doesn't base the classifier edits for the default jars on the current `remapJar` classifier. (The classifier for named jars doesn't really matter considering they're not all that useful)

Loom just sets the `jar` task's classifier to be `dev` unless you modify it, so if you really want `fabric-dev`, you also need to add `jar { archiveClassifier.set("fabric-dev") }`.

**Comment by ChloeDawn** [comment]
Is it possible to skip `-dev` artifacts entirely? I have no need for them.

**Comment by Juuxel** [comment]
`remapJar` needs an input jar to remap, so it's not really possible to skip them. You don't have to use them for anything, though, and I guess you could make a simple `Delete` task to get rid of them if you really want them gone. :smile:
