### ISSUE TITLE
[1.17.1][Loom 0.9-SNAPSHOT] `class_1309.method_5773` does not get remapped to intermediary in the refmap from mojang mappings

### ISSUE THREAD

**Issue by CorgiTaco** [FabricMC/fabric-loom#473]
Generated refmap from build(Mojang names warning) https://gist.github.com/CorgiTaco/f9718553744e3cb1309c002f4e5ea765#file-refmap-json-L18

My mixin(Mojang names warning): https://github.com/CorgiTaco/Enhanced-Celestials/blob/d63926556964ad376114df41f1ab010dc93b1425/src/main/java/corgitaco/enhancedcelestials/mixin/MixinLivingEntity.java#L27-L33

My build.gradle: https://github.com/CorgiTaco/Enhanced-Celestials/blob/f8aca864cdd16f77f29649332a306091e51723a3/build.gradle

This causes the jar to break in production.

**Comment by Logiquo** [comment]
Can confirm the mapping generation is incorrect. For `loom.mappings-layered+hash.961.minecraft.1.17.1` there is 
```
c	atu	net/minecraft/class_1309	net/minecraft/world/entity/LivingEntity
	m	()V	tick	tick	tick
```
which stops MCE from searching the parents.

**Comment by Logiquo** [comment]
@modmuss50 I guess this could be a bug in layer mapping? Could you have a look at this?

**Comment by Logiquo** [comment]
The reason is the mapping fed into ap is incorrect. With a closer look, the problem is layer mapping.
Specifically, Mojang distributes a complete mapping (i.e. contains all field/method names regardless of inheritance relationship) where an intermediary distributes an incomplete mapping (i.e. only put method/field name in super-class).
It will cause the resulting mapping tree

```
<mojang name>: [null, <obf name>]
```

where null should be an intermediary name. This situation would happen for every inheritance method due to the different distribution methods described above.

And `MappingSourceNsSwitch` will fill the null into `<mojang name>`. Which cause the following mapping to be generated

```
<mojang name> <mojang name>
```

**Comment by modmuss50** [comment]
Run `./gradlew build --refresh-dependencies` to fix.
