### ISSUE TITLE
[1.17.1 Mojmap][0.9-Snapshot] Redirect on the method `RenderSystem.setShaderTexture` does not get added to refmap

### ISSUE THREAD

**Issue by CorgiTaco** [FabricMC/fabric-loom#477]
**Mojmap warning**

When creating the jar for my mod Enhanced Celestials, the jar breaks in production and upon closer inspection the refmap entry for my redirect target is missing. I suspicion this may be a side effect of the reported/fixed issue in #473 / #474 

When I reported #473 you can see in the refmap I attached to that issue, that the render system redirect refmap entry is present: https://gist.github.com/CorgiTaco/f9718553744e3cb1309c002f4e5ea765#file-refmap-json-L32

Now in my generated jar after following the instructions to refresh dependencies, this entry is missing and is once again breaking my jar in production. (It works fine in dev environment)

Generated refmap in jar: https://gist.github.com/CorgiTaco/942dde5b63af06fa74c38e38bd889d0f#file-refmap-json-L32-L35

Redirect in question: https://github.com/CorgiTaco/Enhanced-Celestials/blob/f8aca864cdd16f77f29649332a306091e51723a3/src/main/java/corgitaco/enhancedcelestials/mixin/client/MixinWorldRenderer.java#L36-L44

Mixin config: https://github.com/CorgiTaco/Enhanced-Celestials/blob/3509a3e07087e1c685619422304aeaf048f5056f/src/main/resources/enhancedcelestials.mixins.json

build.gradle: https://github.com/CorgiTaco/Enhanced-Celestials/blob/f8aca864cdd16f77f29649332a306091e51723a3/build.gradle

**Comment by Logiquo** [comment]
Can confirm this is an MCE bug. 

The `newOwner.equals(method.getOwner())` in https://github.com/FabricMC/fabric-mixin-compile-extensions/blob/076f13268eddf98c3cff92a03f9e5701f1e6bb0c/src/main/java/net/fabricmc/loom/mixin/MixinMappingProviderTiny.java#L71 cause it stops remapping the desc.

A similar situation also happens here https://github.com/FabricMC/fabric-mixin-compile-extensions/blob/076f13268eddf98c3cff92a03f9e5701f1e6bb0c/src/main/java/net/fabricmc/loom/mixin/MixinMappingProviderTiny.java#L96

@sfPlayer1 Since you write this part in the past, is there some specific reason to have the condition `newOwner.equals(method.getOwner())`? Can I simply remove it to fix the issue?
