### ISSUE TITLE
Loom subproject generating files in the rootproject.

### ISSUE THREAD

**Issue by Darkhax** [FabricMC/fabric-loom#509]
When generating the run configurations for a loom project that is part of a multiproject setup, the run directory and launch files are generated in the root project directory rather than the loom project directory. The launch files for Eclipse and Idea are generated properly and target the correct run directory, the files are just not in the expected location. 

For example the files generate as
```
rootproject/run
rootproject/fabric_client.launch
```
but the expected locations are
```
rootproject/fabric/run
rootproject/fabric/fabric_client.launch
```

A potential cause of this issue might be the use of getRootDir in places like [this](https://github.com/FabricMC/fabric-loom/blob/dev/0.10/src/main/java/net/fabricmc/loom/configuration/ide/RunConfigSettings.java#L292). Based on the Gradle docs this should possibly be getProjectDir.

**Comment by modmuss50** [comment]
Moving the default run dir location is an interesting question, I guess it would make sense to be next to the project.

Easy enough to move the eclipse launch config files as well. 👍

**Comment by modmuss50** [comment]
I have made some improvements to this, please let me know if you have any issues or further suggestions. 👍

**Comment by Foxite** [comment]
I have something similar:
```
rootproject/settings.gradle
rootproject/fabric/build.gradle
rootproject/forge/build.grade
rootproject/shared/build.gradle
```
When I execute fabric's runClient or runServer task, a `run` folder is created in `rootproject`, however I'd like for it to be put in `rootproject/fabric`.

This seems to be because of [this](https://github.com/FabricMC/fabric-loom/blob/dev/0.10/src/main/java/net/fabricmc/loom/task/AbstractRunTask.java#L53), perhaps it should be changed to use getProjectDir() as well, rather than getRootDir().

Right now, I can fix this problem by adding this to fabric/build.gradle:
```
loom.getRunConfigs().getByName("client").runDir("fabric/run")
loom.getRunConfigs().getByName("server").runDir("fabric/run")
```
This seems like it could be better, though.

**Comment by Darkhax** [comment]
> I have made some improvements to this, please let me know if you have any issues or further suggestions. 👍

Hello, the fixes seem to have addressed the initial concerns and have been working fine. We have also had to do something similar to what Foxite has done but that seems to be a separate issue.
