### ISSUE TITLE
Loom build with kapt caused `Multiple output file properties with name 'mixin-ap-main'`

### ISSUE THREAD

**Issue by SettingDust** [FabricMC/fabric-loom#790]
Repo: https://github.com/SettingDust/fabric-kapt-issue

When gradle `compileJava` with kapt it will 👇
```
* What went wrong:
Execution failed for task ':compileJava'.
> Multiple output file properties with name 'mixin-ap-main'
```

Caused by Java and Kapt add property twice
https://github.com/FabricMC/fabric-loom/blob/dev/1.0/src/main/java/net/fabricmc/loom/configuration/CompileConfiguration.java#L262-L277
```
passMixinArguments:98, AnnotationProcessorInvoker (net.fabricmc.loom.build.mixin)
configureMixin:147, AnnotationProcessorInvoker (net.fabricmc.loom.build.mixin)
configureMixin:76, KaptApInvoker (net.fabricmc.loom.build.mixin)
setupMixinAp:271, CompileConfiguration (net.fabricmc.loom.configuration)
```
```
passMixinArguments:98, AnnotationProcessorInvoker (net.fabricmc.loom.build.mixin)
configureMixin:147, AnnotationProcessorInvoker (net.fabricmc.loom.build.mixin)
setupMixinAp:262, CompileConfiguration (net.fabricmc.loom.configuration)
```

**Comment by modmuss50** [comment]
Hi, sorry about this, was caused by a recent hotfix we did...

Many thanks for the simple reproduction mod, makes it much easier for me to test 👍

We should really have an intergration test that uses Kapt, but I seem to be struggling to get it to work as it fails with `NoClassDefFoundError: org/jetbrains/kotlin/gradle/plugin/KaptExtension`. Anyway see the PR with the fix, I manually tested this aginst your repo. 👍
