### ISSUE TITLE
Multiproject: gradle hangs and crashes when they target different Minecraft mappings

### ISSUE THREAD

**Issue by opekope2** [FabricMC/fabric-loom#800]
I have a multiproject mod. There is the 'core' mod, and there are 'glue' mods, which target different Minecraft versions to act as a glue library, and provide stuff to the main library.

Here is a sample project (with no code as it is irrelevant): https://github.com/opekope2/Loom-Mappings-Bug-Demo

When I try to build it with `./gradlew :OptiGUI:build`, it tries to remap the dependency projects. Gradle gets stuck on `:OptiGlue:1.19:remapJar` and `:OptiGlue:1.19.3:remapJar` for several minutes, then it "disappears" or crashes because of "Java heap space"

(Delete every "bin" and "build" folder to clean up for another try)

However, if I build the projects separately, as
```
./gradlew :OptiGlue:1.19:build
./gradlew :OptiGlue:1.19.3:build
./gradlew :OptiGUI:build
```
then everything builds successfully, and gradle doesn't hang or crash.

**Comment by KosmX** [comment]
As far as I know, remapJar and remapSourcesJar tasks does **not** close (free up ~200-500MB) until all remap jar tasks are done...  

Try giving your build more memory.
(I have 12 modules, it requires at least 6 GB memory to not fail)

**Comment by KosmX** [comment]
This is done due to caching, if multiple modules would need the same remapper (remap from-to same mappings) it can be re-used.

If you can run only one remapJar task in one build, other remap tasks won't cache, it can decrease the memory usage.

But I would change remap task caching behavior, as same remapper in the same project is rare (even split-source environments has different sourceSets) but when having multiple targets it can quickly use a lot of memory. (12 modules requires 6 GB to not fail always, 8 GB to be reliable.)
> It may change in loom 1.1, I don't know the changes.

**Comment by opekope2** [comment]
Indeed, increasing the memory *does* fix it, but when I'll have a lot of modules, it would be easier to disable cache or build sequentially by bypassing cache (if possible)
