### ISSUE TITLE
Weird behavior with compileOnlyApi dependencies of mod dependencies

### ISSUE THREAD

**Issue by jpenilla** [FabricMC/fabric-loom#801]
I have a mod library ([`cloud-fabric`](https://github.com/Incendo/cloud)) that declares a `compileOnlyApi` dependency on `org.apiguardian:apiguardian-api:1.1.2` (not a mod). When adding `cloud-fabric` to `modImplementation` in a separate project, it seems like the `compileOnlyApi` dependency isn't properly pulled in, as evidenced by the output of build scans/dependencies task, and the massive amount of warnings on build: https://github.com/jpenilla/squaremap/actions/runs/3762624455/jobs/6395483461#step:7:131
(adding the dependency to `compileOnly` manually is a workaround, which I've since used in the linked repo)

I also have non-mod libraries (for example `cloud-paper`), which declares the same `compileOnlyApi` dependency, and when depending on it using `implementation` in a separate project, I get no similar warnings and the dependency appears in scans/dependencies as expected, which is what leads me to think it's something with loom.

I've spent some time trying to debug this but haven't really gotten anywhere.

`cloud.commandframework:cloud-fabric:1.8.0` is published on maven central, adding it to `modImplementation` is enough to reproduce the issue, to get the warnings just reference an annotated method (for example `StringArgument.builder("");`) (might also need `-Xlint:all`, not sure as I always have it on)

*Every* module in cloud has this `compileOnlyApi` dep, which means not only is the direct dependency lost, but also the dependencies of for example `cloud-core` that `cloud-fabric` also depends on.

**Comment by zml2008** [comment]
Looking into loom's resolver behaviour, I think this is due to differences in Loom's mod* configuration structure compared to the [standard Gradle hierarchy](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management). With a build scan, it becomes clear that Gradle is choosing cloud-fabric's `runtimeElements` configuration when resolving the `modImplementation` configuration:

![image](https://user-images.githubusercontent.com/629092/211983047-6fa38f12-5299-471f-a2e7-ca68b7b8e0d9.png)

This would explain why `compileOnlyApi` dependencies are skipped.

The issue here seems to be a fundamental mismatch between the loom and Gradle `java` plugin configuration hierarchies. In a standard gradle project, configurations are overloaded for three purposes: declaring dependencies, resolving dependencies, and publishing artifacts -- where each configuration only serves one of these purposes. The `implementation` configuration is one of the first time -- it is only used to declare dependencies. The `compileClasspath` and `runtimeClasspath` configurations which are used for actually resolving dependencies both extend the `implementation` configuration. Because these two resolution configurations have different sets of attributes, they can resolve different artifacts and dependency graphs based on the same declaration.

Loom directly resolves the `modImplementation` configuration, remaps one single resolved artifact, and then places the remapped version and single dependency graph into the appropriate target configurations. This prevents the appropriate variant from being resolved depending on use.

I think this is resolvable (not without a bunch of annoyance) by making the loom configuration structure more closely match a normal gradle project. Some remap configurations wouldn't actually be processed, they're just used for declaration, and the remapper would only proceed on the configurations used for resolution. The actual resolution configurations would have to have attributes declared (or copied from the equivalent standard configuration?) in order to instruct Gradle's variant-aware selection to resolve the appropriate variant (see `./gradlew outgoingConfigurations` on a standard java project for the default attributes).

**Comment by jpenilla** [comment]
https://github.com/FabricMC/fabric-loom/compare/dev/1.0...jpenilla:fabric-loom:801 I have a rough poc fix

Not sure if I will have time to complete this to a mergeable state any time soon, so if a maintainer or someone else wants to pick it up, feel free.
