### ISSUE TITLE
modCompile does not work on non-empty jar classifiers

### ISSUE THREAD

**Issue by UpcraftLP** [FabricMC/fabric-loom#82]
the `modCompile` configuration does not work on none-empty jar classifiers, such as `api`.

**Comment by falkreon** [comment]
this is probably the same circumstance I mention in #83

**Comment by UpcraftLP** [comment]
> this is probably the same circumstance I mention in #83

no, the jar definitely exists and I can use it just fine using the `implementation` configuration, but loom seems to not like a jar classifier being present.

**Comment by Chocohead** [comment]
It's not that Loom doesn't like them, more that Loom completely ignores them when it renames jars as part of `modCompile`. Classifiers are not immediately exposed via the artifact API so it's not a hard oversight to make. Think it comes in as an additional property on the artifact rather than part of the module identifier.

**Comment by asiekierka** [comment]
Fixed in 0.2.4.
